version: '3'
services:

  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: unless-stopped
    hostname: 'hostname.lan'
    links:
      - postgresql:postgresql
      - redis:redis
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        postgresql['enable'] = false
        gitlab_rails['db_username'] = "gitlab"
        gitlab_rails['db_password'] = "gitlab"
        gitlab_rails['db_host'] = "postgresql"
        gitlab_rails['db_port'] = "5432"
        gitlab_rails['db_database'] = "gitlabhq_production"
        gitlab_rails['db_adapter'] = 'postgresql'
        gitlab_rails['db_encoding'] = 'utf8'
        redis['enable'] = false
        gitlab_rails['redis_host'] = 'redis'
        gitlab_rails['redis_port'] = '6379'
        external_url 'https://hostname.lan'
        gitlab_rails['gitlab_shell_ssh_port'] = 30022
    ports:
        - "443:443"
        - "80:80"
        - "30022:22"
    volumes:
      - config:/etc/gitlab:rw
      - logs:/var/log/gitlab:rw
      - data:/var/opt/gitlab:rw
    networks:
      - gitlab

  postgresql:
    restart: unless-stopped
    image: postgres:9.6.2-alpine
    environment:
      - POSTGRES_USER=gitlab
      - POSTGRES_PASSWORD=gitlab
      - POSTGRES_DB=gitlabhq_production
    volumes:
      - postgresql:/var/lib/postgresql/data:Z
    networks:
      - gitlab

  redis:
    restart: unless-stopped
    image: redis:3.0.7-alpine
    volumes:
      - redis:/data:Z
    networks:
      - gitlab

networks:
  gitlab:
    external: no

volumes:
  postgresql:
    driver: local
  config:
    driver: local
  logs:
    driver: local
  data:
    driver: local
  redis:
    driver: local
